server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: ${ORIGINS:http://localhost:${server.port},http://localhost:3000}
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: jaccount-service
          uri: lb://jaccount-service
          predicates:
            - Path=/**
        - id: jstorage-service
          uri: lb://jstorage-service
          predicates:
            - Path=/**
        - id: jtascexec-service
          uri: lb://jtascexec-service
          predicates:
            - Path=/**
        - id: jnotification-service
          uri: lb://jnotification-service
          predicates:
            - Path=/**
#      default-filters:
#        TokenRelay=
#  security:
#    oauth2:
#      client:
#        registration:
#          gateway:
#            provider: j-provider
#            client-id: gateway-client-id
#            client-secret: secret_justedlev
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://localhost:${server.port}/login/oauth2/code/{registrationId}"
#            scope: openid, message.read
#        provider:
#          j-provider:
#            issuer-uri: http://localhost:9876
eureka:
  client:
    service-url:
      default-zone: ${DISCOVERY_HOST}