server:
  port: 8765
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      default-filters:
#        TokenRelay=
#  security:
#    oauth2:
#      client:
#        registration:
#          gateway:
#            provider: j-provider
#            client-id: gateway-client-id
#            client-secret: secret_justedlev
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://localhost:${server.port}/login/oauth2/code/{registrationId}"
#            scope: openid, message.read
#        provider:
#          j-provider:
#            issuer-uri: http://localhost:9876
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka