server:
  port: 8765
  error:
    include-stacktrace: never
spring:
  application:
    name: api-gateway
  security:
    user:
      name: ${USERNAME}
      password: ${PASSWORD}
      roles: ${ROLES}
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          jwk-set-uri: ${KEYCLOAK_JWKS_URI}
        opaquetoken:
          introspection-uri: ${KEYCLOAK_INTROSPECTION_ENDPOINT}
          client-id: ${KEYCLOAK_CLIENT_ID}
          client-secret: ${KEYCLOAK_CLIENT_SECRET}
#      client:
#        provider:
#          keycloak:
#            issuer-uri: ${KEYCLOAK_ISSUER_URI}
#            jwk-set-uri: ${KEYCLOAK_JWKS_URI}
#            user-name-attribute: preferred_username
#        registration:
#          api-gateway:
#            client-name: api-gateway
#            client-id: ${KEYCLOAK_CLIENT_ID}
#            client-secret: ${KEYCLOAK_CLIENT_SECRET}
#            provider: keycloak
#            authorization-grant-type: client_credentials
#            scope: openid,resource.read
  cloud:
    gateway:
      #      loadbalancer:
      #        use404: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
      #            allowedOrigins: ${ORIGINS:http://localhost:${server.port},http://localhost:3000}
      #            allowedOrigins: "*"
      #            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users-justedlevhub
          uri: lb://users-justedlevhub
          predicates:
            - Path=/**
        #          filters:
        #            - TokenRelay=
        #            - RemoveRequestHeader=Cookie
        - id: jstorage-service
          uri: lb://jstorage-service
          predicates:
            - Path=/**
        - id: jtascexec-service
          uri: lb://jtascexec-service
          predicates:
            - Path=/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/**
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${DISCOVERY_HOST}
logging:
  level:
    web: debug
    org:
      springframework:
        security: trace

# Custom properties
